name: Injected test
on:
  pull_request:
    branches: [main]
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  mysite-ci:
    runs-on: [self-hosted,linux]
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
      - name: Test
        run: echo "new test"